WebApplication1/Models/ErrorViewModel.cs
namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Presents.Data.Entities;
using Presents.Data;
using Microsoft.EntityFrameworkCore;

namespace PresentsWebApp.Controllers
{
    public class CategoryController : Controller
    {
        private readonly PresentsDbContext context;
        public CategoryController(PresentsDbContext context)
        {
            this.context = context;
        }
        public async Task<IActionResult> Index()
        {
            var categories = await context.Categories.ToListAsync();
            return View(categories);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Category category)
        {
            await context.Categories.AddAsync(category);
            await context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            var category = context.Categories.Find(id);
            if (category == null)
            {
                return NotFound();
            }
            context.Categories.Remove(category);
            await context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

WebApplication1/Controllers/GiftController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Presents.Data.Entities;
using Presents.Data;
using Microsoft.EntityFrameworkCore;

namespace PresentsWebApp.Controllers
{
    public class GiftController : Controller
    {
        private readonly PresentsDbContext context;
        public GiftController(PresentsDbContext context)
        {
            this.context = context;
        }
        public async Task<IActionResult> Index()
        {
            var gifts = await context.Gifts.Include(x => x.Category).ToListAsync();
            return View(gifts);
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(context.Categories, "ID", "Name");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Gift gift)
        {
            await context.Gifts.AddAsync(gift);
            await context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            var gift = context.Gifts.Find(id);
            if (gift == null)
            {
                return NotFound();
            }
            context.Gifts.Remove(gift);
            await context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Download()
        {
            var count = await context.Gifts.CountAsync();
            if (count == 0)
            {
                return NotFound();
            }
            Random random = new Random();
            int r = random.Next(0, count);
            var gift = await context.Gifts.Skip(r).FirstOrDefaultAsync();
            gift.IsTaken = true;
            return View(gift);
        }
    }
}

WebApplication1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication1/Views/Category/Create.cshtml
@model Presents.Data.Entities.Category
<h2 class="text-black">Create category: </h2>
<form asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="Name" class="form-label">Name</label>
        <input asp-for="Name" class="form-control" />
    </div>
    <div class="mb-3">
        <button type="submit" class="btn btn-primary">Submit</button>
        <a asp-action="Index" asp-controller="Category" class="btn btn-secondary">Back</a>
    </div>
</form>

WebApplication1/Views/Category/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model List<Presents.Data.Entities.Category>
<h2 class="text-center">Categories</h2>
<div class="mb-3">
    <a asp-action="Create" asp-controller="Category" class="btn btn-primary">Add Category</a>
    <a asp-action="Index" asp-controller="Home" class="btn btn-secondary">Back</a>
</div>
<table class="table table-bordered table-striped">
    <thead>
        <tr class="table-danger">
            <th>ID</th>
            <th>Name</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.ID</td>
                <td>@item.Name</td>
                <td>
                    <form asp-action="Delete" asp-route-id="@item.ID" asp-controller="Category" method="post" style="display:inline">
                        <button class="btn btn-warning btn-sm">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

WebApplication1/Views/Gift/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Presents.Data.Entities.Gift
<h2 class="text-black">Create gift: </h2>
<form asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="Name" class="form-label">Name</label>
        <input asp-for="Name" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="Decription" class="form-label">Description</label>
        <input asp-for="Decription" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="ImageURL" class="form-label">Image URL</label>
        <input asp-for="ImageURL" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="CategoryID" class="form-label">Category</label>
        <select asp-for="CategoryID" asp-items="ViewBag.Categories" class="form-select"></select>
    </div>
    <div class="mb-3">
        <label class="form-label">Taken</label>
        <div>
            <input type="radio" asp-for="IsTaken" value="true" id="true" />
            <label for="taken-true">Yes</label>
            <br />
            <input type="radio" asp-for="IsTaken" value="false" id="false" />
            <label for="taken-false">No</label>
        </div>
    </div>
    <div class="mb-3">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

WebApplication1/Views/Gift/Download.cshtml
@model Presents.Data.Entities.Gift

<div class="padding: 100px text-center">
    <h1 class="display-4 mb-lg-5 text-center" style="font-family: 'Times New Roman', Times, serif; padding: 80px">Изтеглен подарък: </h1>
    <p class="mb-3 text-center text-dark text-black" style="font-size:36px; font-family: 'Times New Roman' , Times, serif;">@Model.Name - @Model.Decription</p>
    <br />
    <br />
    <a asp-controller="Home" asp-action="Index" class="btn btn-secondary d-inline btn-lg">Back</a>
</div>

WebApplication1/Views/Gift/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model List<Presents.Data.Entities.Gift>
<h2 class="text-center">Gifts</h2>
<table class="table table-bordered table-striped">
    <thead>
        <tr class="table-danger">
            <th>Name</th>
            <th>Description</th>
            <th>Image URL</th>
            <th>Category</th>
            <th>Taken</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.Decription</td>
                <td><img src="@item.ImageURL" width="400" height="250" /></td>
                <td>@item.Category.Name</td>
                <td>@item.IsTaken</td>
                <td>
                    <form asp-action="Delete" asp-route-id="@item.ID" asp-controller="Gift" method="post" style="display:inline">
                        <button class="btn btn-danger btn-sm">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

WebApplication1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<style>
    body {
        background: linear-gradient( rgba(20, 34, 60, 0.65), rgba(33, 57, 91, 0.75) ), url("https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&q=80&w=2070");
        background-size: cover;
        background-position: center;
        background-attachment: fixed;
        background-repeat: no-repeat;
        color: white;
    }


    .flake {
        position: fixed;
        top: -20px;
        width: 8px;
        height: 8px;
        background: white;
        border-radius: 50%;
        opacity: 0.7;
        pointer-events: none;
        z-index: 99999;
        animation: fall2 linear forwards;
    }

    @@keyframes fall2 {
        0% {
            transform: translateX(0) rotate(0deg);
        }
        50% {
            transform: translateX(30px) rotate(180deg);
        }
        100% {
            transform: translateY(100vh) translateX(-30px) rotate(360deg);
        }
    }


    html, body {
        height: 100%;
    }

    body {
        display: flex;
        flex-direction: column;
    }

    footer {
        margin-top: auto;
    }

</style>

<script>
    function newSnowflake() {
        const flake = document.createElement("div");
        flake.classList.add("flake");

        // Размери
        let size = Math.random() * 6 + 4;
        flake.style.width = size + "px";
        flake.style.height = size + "px";

        // Позиция
        flake.style.left = Math.random() * 100 + "vw";

        // Прозрачност
        flake.style.opacity = Math.random() * 0.7 + 0.3;

        // Продължителност на падането
        flake.style.animationDuration = Math.random() * 5 + 4 + "s";

        // Леко отклонение наляво/надясно
        flake.style.setProperty("--drift", (Math.random() * 60 - 30) + "px");

        document.body.appendChild(flake);

        // Премахване след края
        setTimeout(() => flake.remove(), 9000);
    }

    // Прави нова снежинка на всеки 120ms
    setInterval(newSnowflake, 120);
</script>



<div class="text-center">
    <h1 class="display-4 mb-5"
        style="font-family: 'Times New Roman', Times, serif; padding: 100px;">
        Presents for Christmas
    </h1>

    <div class="d-flex flex-column align-items-center gap-3">
        <a asp-action="Create" asp-controller="Gift" class="btn btn-primary btn-lg w-50">
            Add a present
        </a>

        <a asp-action="Download" asp-controller="Gift" class="btn btn-success btn-lg w-50">
            Pull a present
        </a>
    </div>
</div>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Create">Add Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gift" asp-action="Index">All Presents</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>